import numpy as np

vehicle_data = {
    'SubaruSti': {"year": 2016,
                  "make": "Subaru",
                  "model": "WRX Sti",
                  "weight": 3200,
                  "steer_ratio": 16.5,
                  "init_x_pos": 0,
                  "init_y_pos": 0,
                  "head_angle": 0,  # <- vehicle heading angle
                  "width": 6,
                  "length": 19.3,
                  "hcg": 1,
                  "lcgf": 4.88,
                  "lcgr": 6.96,
                  "wb": 11.84,
                  "track": 6.6,
                  "f_hang": 3.2,
                  "r_hang": 4.1,
                  "tire_d": 2.716666667,
                  "tire_w": 0.866666667,
                  "izz": 2500,
                  "vx_initial": 0,
                  "vy_initial": 0,
                  "omega_z": 0,
                  "striking": True},

    'FordFusion': {"year": 2008,
                   "make": "Ford",
                   "model": "Fusion",
                   "weight": 3574.2,
                   "steer_ratio": 16.5,
                   "init_x_pos": 0,
                   "init_y_pos": 0,
                   "head_angle": 0,  # <- vehicle heading angle
                   "width": 6,
                   "length": 190 / 12,
                   "hcg": 1,
                   "lcgf": 107 / 24,  # <- 50/50 weight distribution
                   "lcgr": 107 / 24,
                   "wb": 107 / 12,
                   "track": 6.6,
                   "f_hang": 40 / 12,
                   "r_hang": 4.1,
                   "tire_d": 2.716666667,
                   "tire_w": 0.866666667,
                   "izz": 2336.3,
                   "vx_initial": 0,
                   "vy_initial": 0,
                   "omega_z": 0,
                   "striking": True},

    'barrier': {"weight": 1000000,
                "width": 1,
                "length": 5,
                "lcgf": 2,
                "lcgr": 2,
                "f_hang": 0.5,
                "r_hang": 0.5,
                "wb": 0.25,
                "tire_d": 0.25,
                "tire_w": 0.25,
                "izz": 1000000,
                "vx_initial": 0,
                "vy_initial": 0,
                "omega_z": 0,
                "head_angle": 180,
                "striking": False}
}
